
exports.AREA_DESCRIPTION_FORMAT_JPG = 0;
exports.AREA_DESCRIPTION_FORMAT_GIF = 1;
exports.AREA_DESCRIPTION_FORMAT_VIDEO = 2;
exports.AREA_DESCRIPTION_FORMAT_MAP = 3;
exports.AREA_DESCRIPTION_FORMAT_STREET_VIEW = 4;
exports.AREA_DESCRIPTION_FORMAT_PNG = 5;

exports.MAIN_ITEM_COVER_NONE = 0;
exports.MAIN_ITEM_COVER_BOX = 1;
exports.MAIN_ITEM_COVER_EGG = 2;

exports.TYPE_QUESTION_ICON = 0;
exports.TYPE_QUESTION_TEXT = 1;
exports.TYPE_QUESTION_NO_TIMER = 2;
exports.TYPE_QUESTION_NO_ICON = 3;
exports.TYPE_QUESTION_NONE = 4;

exports.AREA_RESOLUTION_BEHAVIOR_SELECT = 0;
exports.AREA_RESOLUTION_BEHAVIOR_JOIN = 1;
exports.AREA_RESOLUTION_BEHAVIOR_MAP = 2;
exports.AREA_RESOLUTION_BEHAVIOR_INPUT_TEXT = 3;

exports.AREA_RESOLUTION_TYPE_TEXT = 0;
exports.AREA_RESOLUTION_TYPE_VISUAL = 1;
exports.AREA_RESOLUTION_TYPE_VISUAL_ITUNES = 2;

exports.AREA_RESOLUTION_LAYOUT_VERTICAL = 1;
exports.AREA_RESOLUTION_LAYOUT_HORIZONTAL = 2;

exports.ACTION_SUCCESS = 1;
exports.ACTION_FAIL = 0;

exports.TIME_BACKGROUND_FADE_OUT = 1000;
exports.DELAY_HIDE_QUESTION = 500;
exports.DELAY_SETUP_QUESTION = 400;
exports.DELAY_SHOW_QUESTION = 1200;
exports.TIME_HIDE_DESCRIPTION = 3000;
exports.TIME_QUESTION_DEFAULT = 30000;

exports.TIMER_DECREASE_DEFAULT = 5;

exports.MAX_GEO_DISTANCE_SUCCESS = 0.5;